In [1]:
# 1. Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

# 2. Примеры создания массивов

# Создание массива из обычного списка Python
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)

# Создание двумерного массива из списка списков
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_data)
print("Двумерный массив:\n", matrix)

# Создание массива из нулей
zeros_array = np.zeros((3, 4))  # Массив 3x4, заполненный нулями
print("Массив из нулей (3x4):\n", zeros_array)

# Создание массива из единиц
ones_array = np.ones((2, 3), dtype=np.int32)  # Массив 2x3 целых чисел
print("Массив из единиц (2x3):\n", ones_array)

# Создание массива с помощью arange (аналог range)
range_array = np.arange(0, 10, 2)  # Числа от 0 до 10 с шагом 2
print("Массив от np.arange(0, 10, 2):", range_array)

# Создание массива с линейным распределением
linspace_array = np.linspace(0, 1, 5)  # 5 чисел равномерно от 0 до 1
print("Массив от np.linspace(0, 1, 5):", linspace_array)

# 3. Демонстрация атрибутов массива
print("\n" + "="*50)
print("Демонстрация атрибутов массива:")
print("Исходный массив matrix:")
print(matrix)

# Форма (shape) массива - размерность по каждой оси
print("Форма массива (shape):", matrix.shape)

# Тип данных (dtype) массива
print("Тип данных массива (dtype):", matrix.dtype)

# Размер массива (общее количество элементов)
print("Размер массива (size):", matrix.size)

# Количество измерений
print("Количество измерений (ndim):", matrix.ndim)

# 4. Примеры индексирования и срезов
print("\n" + "="*50)
print("Индексирование и срезы:")

# Получение отдельного элемента
# В NumPy индексация начинается с 0
element = matrix[1, 2]  # Элемент во второй строке, третьем столбце
print(f"Элемент matrix[1, 2]: {element}")

# Срезы (slicing)
# Синтаксис: start:stop:step
row_slice = matrix[1, :]  # Вторая строка целиком
print(f"Вторая строка (matrix[1, :]): {row_slice}")

col_slice = matrix[:, 1]  # Второй столбец целиком
print(f"Второй столбец (matrix[:, 1]): {col_slice}")

# Подмассив из первых двух строк и двух столбцов
submatrix = matrix[:2, :2]
print(f"Подмассив 2x2 (matrix[:2, :2]):\n{submatrix}")

# Срез с шагом
every_other_row = matrix[::2, :]  # Каждая вторая строка
print(f"Каждая вторая строка (matrix[::2, :]):\n{every_other_row}")

# 5. Примеры векторных операций и базовых статистик
print("\n" + "="*50)
print("Векторные операции и статистика:")

# Создадим два массива для операций
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Поэлементное сложение
sum_result = arr1 + arr2
print(f"Поэлементное сложение: {arr1} + {arr2} = {sum_result}")

# Поэлементное умножение
mult_result = arr1 * arr2
print(f"Поэлементное умножение: {arr1} * {arr2} = {mult_result}")

# Поэлементное возведение в степень
power_result = arr1 ** 2
print(f"Квадрат каждого элемента: {arr1} ** 2 = {power_result}")

# Базовые статистические функции
print("\nБазовые статистики для массива arr1:", arr1)

# Среднее значение
mean_value = np.mean(arr1)
print(f"Среднее значение (mean): {mean_value}")

# Сумма всех элементов
sum_value = np.sum(arr1)
print(f"Сумма всех элементов (sum): {sum_value}")

# Минимальное и максимальное значение
min_value = np.min(arr1)
max_value = np.max(arr1)
print(f"Минимальное значение (min): {min_value}")
print(f"Максимальное значение (max): {max_value}")

# Стандартное отклонение
std_value = np.std(arr1)
print(f"Стандартное отклонение (std): {std_value:.2f}")

# Медиана
median_value = np.median(arr1)
print(f"Медиана (median): {median_value}")

# Пример с двумерным массивом
print("\nСтатистики для двумерного массива:")
print("Исходный массив:\n", matrix)

# Среднее по всему массиву
print(f"Среднее по всему массиву: {np.mean(matrix)}")

# Среднее по столбцам (ось 0)
print(f"Среднее по столбцам (axis=0): {np.mean(matrix, axis=0)}")

# Среднее по строкам (ось 1)
print(f"Среднее по строкам (axis=1): {np.mean(matrix, axis=1)}")

# Дополнительный пример: трансляция (broadcasting)
print("\n" + "="*50)
print("Пример трансляции (broadcasting):")

# Скаляр можно применить ко всему массиву
scaled_matrix = matrix * 10
print(f"Матрица, умноженная на 10:\n{scaled_matrix}")

# Можно применять операции между массивами разных размеров
vector = np.array([1, 2, 3])
broadcast_result = matrix + vector  # Вектор добавляется к каждой строке
print(f"Трансляция: матрица + вектор [1,2,3]:\n{broadcast_result}")

Массив из списка: [1 2 3 4 5]
Двумерный массив:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив из нулей (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив из единиц (2x3):
 [[1 1 1]
 [1 1 1]]
Массив от np.arange(0, 10, 2): [0 2 4 6 8]
Массив от np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

Демонстрация атрибутов массива:
Исходный массив matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма массива (shape): (3, 3)
Тип данных массива (dtype): int64
Размер массива (size): 9
Количество измерений (ndim): 2

Индексирование и срезы:
Элемент matrix[1, 2]: 6
Вторая строка (matrix[1, :]): [4 5 6]
Второй столбец (matrix[:, 1]): [2 5 8]
Подмассив 2x2 (matrix[:2, :2]):
[[1 2]
 [4 5]]
Каждая вторая строка (matrix[::2, :]):
[[1 2 3]
 [7 8 9]]

Векторные операции и статистика:
Поэлементное сложение: [1 2 3 4 5] + [10 20 30 40 50] = [11 22 33 44 55]
Поэлементное умножение: [1 2 3 4 5] * [10 20 30 40 50] = [ 10  40  90 160 250]
Квадрат каждого элемента: [1 2 3 4 5] ** 2 = [ 1  4  9 16 25]

Базовые статистики для